### ISSUE TITLE
feat: Add Intel GPU Support via SYCL on Linux platform

### ISSUE THREAD

**Issue by xiangyang-95** [janhq/cortex.llamacpp#107]
**Problem**
Add support for Intel GPU via Intel OneAPI SYCL on Linux

**Success Criteria**
- [ ] Add Linux Runner with Intel OneAPI container
- [ ] Add build steps using Intel OneAPI container
- [ ] Add app running steps with Intel OneAPI container

**Additional context**
N/A

**Comment by dan-homebrew** [comment]
I am merging this issue into https://github.com/janhq/cortex.cpp/issues/470

- llama.cpp also supports sycl now
- We may work more closely with Intel on Lunar Lake support
