### ISSUE TITLE
feat: [support stream_option for OpenAI API compatible]

### ISSUE THREAD

**Issue by nguyenhoangthuan99** [janhq/cortex.llamacpp#265]
**Problem**
- field: `stream_options`
- object or null
- Optional
Defaults to null. Options for streaming response. Only set this when you set stream: true.
{"include_usage": boolean
}
Optional
If set, an additional chunk will be streamed before the data: [DONE] message. The usage field on this chunk shows the token usage statistics for the entire request, and the choices field will always be an empty array. All other chunks will also include a usage field, but with a null value.

reference: https://platform.openai.com/docs/api-reference/chat/create#chat-create-stream_options

related issue: https://github.com/janhq/internal/issues/160

**Comment by gabrielle-ong** [comment]
✅ QA: on `cortex.llama-cpp v0.1.37-01.11.24`
API request: `v1/chat/completions`
```
"stream_options": {
        "include_usage": false | true
},
```

### `include_usage = false`:
![Image](https://github.com/user-attachments/assets/12debbb1-9700-4038-a8c4-b5fd1a6f71b9)

### `include_usage = true`: additional chunk before [DONE] showing token usage statistics
![Image](https://github.com/user-attachments/assets/a1c554b5-c5d9-418d-95f5-2b892a44c909)

![Image](https://github.com/user-attachments/assets/d5267958-6422-473b-8802-fde6419d4ac3)
