### ISSUE TITLE
feat: Nightly build release name should map with commit ID from upstream repo llama.cpp

### ISSUE THREAD

**Issue by hiento09** [janhq/cortex.llamacpp#303]
Implement functionality to ensure that nightly build release names are automatically mapped to the corresponding commit ID from the upstream repository llama.cpp. This feature will enhance traceability and consistency between builds and their source code versions. The implementation should:
- Retrieve the latest commit ID from the upstream repo during the nightly build process.
- Use the commit ID as part of the release name format.
- Ensure the process is seamless and doesn't disrupt existing build workflows.

This improvement will simplify debugging and version tracking for nightly builds.

**Comment by gabrielle-ong** [comment]
Hi @hiento09, just to confirm, the aligned releases will be marked as pre-releases or latest release?

Currently `0.1.40-b4248` is marked as pre-release, and the latest release is `0.1.40` https://github.com/janhq/cortex.llamacpp/releases

**Comment by hiento09** [comment]
Hi @gabrielle-ong,
I want to clearly distinguish between the two tags as follows:

The `latest` tag follows the semantic version format and is defined by us. This is used for publishing the latest release, and it cannot be changed for now because our cortex code currently installs the `cortex.llamacpp` engine using logic based on semantic versioning.

For the `nightly` tag, the tagging logic works as follows: Every night, I will check the `latest` tag to determine its current version. For example, if the current version is `v0.1.40`, I will pull the latest llama-cpp upstream and use the semantic format but append `-<llamacpp_release_name>` to the end. This way, the nightly pre-release tag will have a format like `v0.1.40-b....`

**Comment by gabrielle-ong** [comment]
Thanks @hiento09, got it - latest tag will remain our semantic version format. 
Marking as complete, thank you!
