### ISSUE TITLE
feat: CI for VNNI support

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.llamacpp#60]
**Problem**
Lack support for VNNI

AVX-512 Vector Neural Network Instructions (VNNI) 

**Success Criteria**

**Additional context**

**Comment by dan-homebrew** [comment]
@vansangpfiev I'm shifting this to Sprint 20, to triage as part of initial llama.cpp support

**Comment by dan-homebrew** [comment]
@vansangpfiev Quick check: is this still in scope for Sprint 21, or should we push to Sprint 22?

**Comment by vansangpfiev** [comment]
Please move this ticket to Sprint 22

**Comment by dan-homebrew** [comment]
@vansangpfiev Is this ticket still valid, or can I archive it?

**Comment by vansangpfiev** [comment]
Please archive it, thank you
