### ISSUE TITLE
feat: [Windows] CI for AMD RoCM support

### ISSUE THREAD

**Issue by hiro-v** [janhq/cortex.llamacpp#9]
**Problem**
- Lack support for AMD RoCM on Windows

**Success Criteria**
- CI pipeline on hosted Github action runner
- Cortex llama.cpp support for AMD RoCM

**Steps**
**BUILD**
- [x] Register github action runner for Windows AMD
- [x] Install Visual Studio with C++
- [x] Install HIP SDK for Windows
- [x] choco install cmake llvm ninja strawberryperl
- [x] PATH=C:\Program Files\AMD\ROCm\5.7\bin

- [x] Build command
```
cmake -S ./nitro_deps -B ./build_deps/nitro_deps
cmake --build ./build_deps/nitro_deps --config Release
mkdir -p build
cd build
cmake -G Ninja -DAMDGPU_TARGETS=gfx1100 -DLLAMA_HIPBLAS=ON -DCMAKE_C_COMPILER="C:\Program Files\AMD\ROCm\5.7\bin\clang.exe" -DCMAKE_CXX_COMPILER="C:\Program Files\AMD\ROCm\5.7\bin\clang++.exe" -DCMAKE_BUILD_TYPE=Release -DLLAMA_NATIVE=OFF -DLLAMA_BUILD_SERVER=ON -DLLAMA_BLAS=ON -DBUILD_SHARED_LIBS=OFF -DWHISPER_SDL2=ON -DLLAMA_HIPBLAS=ON -DAMDGPU_TARGETS="gfx803;gfx900;gfx906:xnack-;gfx908:xnack-;gfx90a:xnack+;gfx90a:xnack-;gfx940;gfx941;gfx942;gfx1010;gfx1012;gfx1030;gfx1100;gfx1101;gfx1102" ..
```
- [x] Replace `-lm.lib` -> `-lmsvcrt.lib` in `build/build.ninja`
- [x] Run build command after the fix: `cmake --build . --config Release`

**INFERENCE**
- [x] Install HIP SDK so that it has `rocblas` and `rocm` in `C:\Program Files\AMD\ROCm\5.7\bin` (We can discover the ability to package this and put into the same directory similar to what we did with CUDA)
- [x] Usage
```
cp build_deps/bin/zlib.dll build/
$env:HIP_VISIBLE_DEVICES = "1" # Choose external card instead of integrated card
$env:HSA_OVERRIDE_GFX_VERSION = "11.0.0" # AMD Radeon 7600 (however as the target is for multiple targets, it should be fine. However in order to make it work with 
.\nitro.exe
```

**Comment by dan-homebrew** [comment]
Merged into https://github.com/janhq/cortex.cpp/issues/323
